### ISSUE TITLE
Some users cannot edit Journals with TinyMCE/Default Text Page Sheet

### ISSUE THREAD

**Issue by CeaneC** [mclemente/fvtt-module-polyglot#308] opened 2023-08-13 12:08 UTC
**Describe the bug**
One of my players is unable to edit his journals when Polyglot is enabled. A `TypeError` is logged in the console, see screenshots for the error. This only occurs when using the TinyMCE and Default Text Page Sheet (which I think is ProseMirror?) editors - Markdown works fine. He's also the only player affected by the issue; his journals work fine for me.

**To Reproduce**
1. Open a journal
2. Open a page on the journal
3. Edit the page
4. Have the edit sheet be set to TinyMCE or Default Text Page Sheet
5. See that you cannot edit the journal, and an error is logged in the console

**Expected behavior**
The journal page is editable

**Screenshots**
The edit page on the left, which is missing all of the formatting options and doesn't let the player type in it:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/43473593/ed92071c-7bd7-4e0f-9d51-4e062f141983)

The error that gets logged in the console when opening the edit page:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/43473593/a7cccccf-e3bd-4b57-aa32-65ccb2494693)

 - Game System and version: DnD5e 2.3.0
 - Polyglot Version 2.0.0 and 2.1.0 (updated to 2.1.0 after the problem was noticed in 2.0)
 - Are you using Babele? No
 - Chrome version 115.0.5790.171 (Official Build) (64-bit). Also tested in Edge with the same results

**Additional context**
I've tested it with only Polyglot and libWrapper enabled, and the issue persists for him. I do not use Monk's Journal Enhancements.

**Comment by mclemente** [comment] 2023-08-13 19:58
I can't reproduce that error. Could you try opening Polyglot's Language Settings and saving/resetting it and check if the error persists?

**Comment by CeaneC** [comment] 2023-08-14 08:38
Found the cause - he had a custom language on his character sheet in the "Special" section, that hadn't been added to the Custom Languages in Polyglot's General Settings.

**Comment by mclemente** [comment] 2023-08-14 17:30
I see, I managed to reproduce with Special languages.

> After adding it to the Custom Languages, he can edit his journal again

That shouldn't have been needed, though, this was a bug. It should be fixed on v2.1.1 now.

**Closed** 2023-08-17 18:05 UTC
Labels: bug
